### ISSUE TITLE
langCode

### ISSUE THREAD

**Issue by sysmat** [emanuelefricano93/frxjs-Ngx-Timeline#13]
- is it possible to have another language support or contribute, we need Slovenian

**Comment by emanuelefricano93** [comment]
Hello @sysmat,

https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/blob/master/projects/ngx-timeline/src/lib/models/NgxConfigObj.ts

You can have a look here, and try to add a key for Slovenian language with the date configuration you need.
Try to do a PR, in case of issue let me know :)

**Comment by sysmat** [comment]
- The problem is that angular pipe doesn't support it.
- I fork it and add it to supportedLanguageCodes, NgxDateObjMap, ...

```
RROR Error: NG02100: InvalidPipeArgument: 'Missing locale data for the locale "sl".' for pipe 'DatePipe'
```

**Comment by sysmat** [comment]
@emanuelefricano93 thx for replay

**Comment by emanuelefricano93** [comment]
Hello @sysmat ,

I am applying the support for slovenian and portuguese :) 
I will release in some minutes.

**Comment by emanuelefricano93** [comment]
Version 1.2.3 just released
https://www.npmjs.com/package/@frxjs/ngx-timeline
Let me know and enjoy the timeline :)

**Comment by sysmat** [comment]
It works like a charm, thx

**Comment by emanuelefricano93** [comment]
Perfect, let's meet in Ljubljana :D, kidding.

Have a nice day!

**Comment by sysmat** [comment]
Yea, it would be great
