### ISSUE TITLE
greeting

### ISSUE THREAD

**Issue by Bouda1010** [emanuelefricano93/frxjs-Ngx-Timeline#15]
1.changeSideInGroup not working when i use map method i returns (changeSideInGroup is not iterable )
(fieldsToCheckEventChangeSideInGroup[this.changeSideInGroup] is not iterable (cannot read property undefined))

2.how can i change the colors with scss?

thanks

**Comment by emanuelefricano93** [comment]
Hello @Bouda1010,

To change the color you can use ngDeep, or like described in the example page you can use a custom class (let's imagine the name of the custom class is inter that you can provide in input).
Your scss will be this and you can update all the css options you need.

::ng-deep ngx-timeline.inter {
  .period-container {
    background: blue !important;
    .period-inner-container {
      background: blue !important;
    }
  }
  .line:not(.first-line):not(.last-line) {
    background-color: lightgrey !important;
  }
  .center-icon-container .icon {
    background: blue !important;
  }
}

For the other issue I did not fully understand the problem, but you can check from here and from the code and try to understand the issue.
https://emanuelefricano93.github.io/frxjs-Ngx-Timeline/

**Comment by ttiimmothy** [comment]
Can I set the position ON_LEFT and ON_RIGHT for the event individually?
From NgxTimeEvent.t.ds,
/**
 * Item used inside the timeline
 */
export interface NgxTimelineItem {
    type?: string;
    position?: NgxTimelineItemPosition.ON_LEFT | NgxTimelineItemPosition.ON_RIGHT;
    periodInfo?: NgxTimelinePeriodInfo;
    eventInfo?: NgxTimelineEvent;
}
export declare enum NgxTimelineItemPosition {
    ON_LEFT = "ON_LEFT",
    ON_RIGHT = "ON_RIGHT"
}

If yes, how to set? Thanks

**Comment by emanuelefricano93** [comment]
Hello @ttiimmothy 

I have just realised the new version 1.2.6
In the sample page you can see how the event with 'Title 4' was set on the Right
You can check the details in this commit: https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/commit/1cca0e55d6a7dc0072ff2e5dcd85518df6447f1a

Basically I have added the to NgxTimelineItem the itemPosition?: NgxTimelineItemPosition attribute.
You can then set it to NgxTimelineItemPosition. ON_LEFT or NgxTimelineItemPosition. ON_RIGHT



You can check here (this an example that shows how you can set your events)
...
{ id: 4, description: 'This is the description of the event 4', timestamp: nextMonth, title: 'title 4', itemPosition: NgxTimelineItemPosition.ON_RIGHT }
...

https://emanuelefricano93.github.io/frxjs-Ngx-Timeline/

**Comment by ttiimmothy** [comment]
Thanks. One more question: May I set a hyper link in the description?
