### ISSUE TITLE
Added tr language support

### ISSUE THREAD

**Issue by organizeleriki** [emanuelefricano93/frxjs-Ngx-Timeline#16]
Your project is really good but I need Turkish language support. Can you add Turkish language support to your project? Or maybe added pass all languages control with browser like `navigator.languages`  😅

**Comment by emanuelefricano93** [comment]
Hello @organizeleriki, let me add the Turkish language :)

**Comment by emanuelefricano93** [comment]
Hello @organizeleriki, check version 1.2.5 with the Turkish language.
You can already try from the example page: https://emanuelefricano93.github.io/frxjs-Ngx-Timeline/
