### ISSUE TITLE
Is there a possility to include pt language on 1.1.0 version?

### ISSUE THREAD

**Issue by edu1525** [emanuelefricano93/frxjs-Ngx-Timeline#17]
I'm using your library on my Angular 10 project, but I need the portuguese language. Is it possible to add portuguese support on 1.1.0 version? 

The 1.2.6 version doesn't work with Angular 10 =(

**Comment by emanuelefricano93** [comment]
Hello @edu1525, I am sorry but I think it would be not a best practice, I would advise you to try to update your project in order to make it better and also for other improvements.
Try to see this issue as a way to update it :)
