### ISSUE TITLE
Sort by date grouping

### ISSUE THREAD

**Issue by Maflend** [emanuelefricano93/frxjs-Ngx-Timeline#25]
Hello. I would like to be able to specify how I want to sort the groupings.
The default is sorted from top to bottom in ascending order. But I want to see up-to-date information first and then outdated information

**Comment by emanuelefricano93** [comment]
Hello @Maflend 
from the demo app page
https://emanuelefricano93.github.io/frxjs-Ngx-Timeline/

you can try to revert the sort order

As described in the readme you can set the property reverseOrder to true

**Comment by Maflend** [comment]
Sorting doesn't work if I set "Group events by" = Year.
I expect that when sorting reverce, 2024 will go first and then 2023.
If I select "Group events by" = Month Year, then everything is sorted correctly

**Comment by Maflend** [comment]
![image](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/59286805/6f6ae356-bd6f-4d9a-bf12-33fec1ac62d9)
![image](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/59286805/17ed8a2d-9c16-499e-a946-a5cf9d9b1c13)

**Comment by emanuelefricano93** [comment]
Ok this is another point :) let me check and I will release the new version soon

**Comment by emanuelefricano93** [comment]
Hello @Maflend ,

Just released version 2.2.1 with the fix requested
Here you can check the fix: https://emanuelefricano93.github.io/frxjs-Ngx-Timeline/

Thanks again to raise the issue and to use the library!
Let me know if we can close the issue

**Comment by Maflend** [comment]
@emanuelefricano93 
Cool. You can close. Thank you!!!

**Comment by emanuelefricano93** [comment]
Perfect :)
