### ISSUE TITLE
Custom language - fe polish?

### ISSUE THREAD

**Issue by mateo9x** [emanuelefricano93/frxjs-Ngx-Timeline#27]
Hello,

Can i by myself somehow add my own language? I'm really missing polish language, because of my app language, and it is realy frustrating at this moment.. I be grateful for some kind of guide?

Cheers

**Comment by emanuelefricano93** [comment]
Hallo take a look to this pr and tra to add it :)
https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/pull/26
Otherwise tomorrow i can do it

**Comment by emanuelefricano93** [comment]
Hello @mateo9x  I have added polish in version 17.0.1 :)

**Comment by mateo9x** [comment]
thx m8! <3
