### ISSUE TITLE
Dynamic Data adding

### ISSUE THREAD

**Issue by HalilAkduman** [emanuelefricano93/frxjs-Ngx-Timeline#28]
Hi, i have a dynamic dataset. When i'm trying to add more event to my data it doesnt render on screen. I have tried using changeDetectorRef it doesnt work. Also ı tried converting my data type to subject and rendering on screen with | async pipe also didnt work. Do you have a solution for this problem ?

Thanks :)

**Comment by emanuelefricano93** [comment]
Hello @HalilAkduman ,

Can you please send me a stackblitz in order to at least test your issue?

**Comment by emanuelefricano93** [comment]
Release [v17.0.2](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/tree/v17.0.2) fix this issues
