### ISSUE TITLE
ChangeSideInGroup bug when adding new event

### ISSUE THREAD

**Issue by HalilAkduman** [emanuelefricano93/frxjs-Ngx-Timeline#29]
Hey, 
My setting changeSideInGroup is set to NgxTimelineEventChangeSideInGroup.ALL.
this is my initial events. 
`  events: NgxTimelineEvent[] = [
    {
      description: '',
      id: uuidv4(),
      title: 'asd',
      timestamp: new Date('Tue Jan 25 2024 13:18:47 GMT+0300 (GMT+03:00)')
    },
    {
      description: '',
      id: uuidv4(),
      title: 'asd',
      timestamp: new Date('Tue Jan 26 2024 13:18:47 GMT+0300 (GMT+03:00)')
    },
    {
      description: '',
      id: uuidv4(),
      title: 'asd',
      timestamp: new Date('Tue Jan 30 2024 13:18:47 GMT+0300 (GMT+03:00)')
    }
  ];`

When adding new event with this.events.push(event) the first event reveals the same side of last event.
![Ekran görüntüsü 2024-02-05 104031](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/103941704/33d0cfc8-6a2d-4750-88e9-19aea4a167c4)

Thank you for responding so quickly :)

**Comment by emanuelefricano93** [comment]
Hello @HalilAkduman,

Let me take a look, are you using the version 17.0.2 right?

**Comment by HalilAkduman** [comment]
Thank you for your response. I got it now :)

**Comment by emanuelefricano93** [comment]
But you gave me an idea, I will change a bit the implementation to add a new functionality to allow also the change despite of the group :)

**Comment by HalilAkduman** [comment]
> But you gave me an idea, I will change it a bit to add a new functionality to allow also the change despite the group :)
> 
> I have done the update in version 17.0.3, so you can choose all and will change the side also across groups

I'm using 17.0.3 and it works like a charm. Thank you :)
