### ISSUE TITLE
Issue for the description 

### ISSUE THREAD

**Issue by Monali-Zala** [emanuelefricano93/frxjs-Ngx-Timeline#31]
![tmp_9c9b9c1a-2d50-40e2-80c2-9727babec3e6](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/112300828/19496787-3657-4a07-bf4e-25ed5eae8546)

**Comment by Monali-Zala** [comment]
In the description , It is store in database with html tags but I want to show the text with the formatting according to that tag.
Example:

1. Done
So It should look like this

**Comment by emanuelefricano93** [comment]
Hello @Monali-Zala this should not be really an issue with the library anyway a solution you could use it is this one

```
<ng-template #myTemplate>
  <div [innerHTML]="htmlString"></div>
</ng-template>
```

You should create an ng-template and then set your tag html that comes from the DB inside a string "htmlString" for instance.
Then you should provide this template to the library :) try with this approach please and let me know

**Comment by Monali-Zala** [comment]
I tried to do as per your suggestion but it is not working
i am attaching my html code for reference
<td *ngFor="let comment of comments; let i = index">
                        <div class="timeline-container">
                          <ngx-timeline
                            [events]="[{ timestamp: comment.creationTime , title:  comment.createdByUser.firstName, description: comment.text}]"
                            [reverseOrder]=true>
                            
                          </ngx-timeline>
                           <ng-template let-event>
                              <div class="timeline-event">
                                <div class="timeline-event-header">
                                  <span class="username">{{ event.title }}</span>
                                  <span class="date">{{ event.timestamp | date: "MMM dd yyyy hh:mm" }}</span>
                                </div>
                                <div [innerHTML]="event.description"></div>
                              </div>
                            </ng-template>
                          </div>
                      </td>

**Comment by Monali-Zala** [comment]
Hello I used this approach
<ng-template #myTemplate>
  <div [innerHTML]="htmlString"></div>
</ng-template>
But not working as I expected.

**Comment by emanuelefricano93** [comment]
Ok I understand what you need, I can try to work on a new feature that will be released in the v17.0.4

**Comment by emanuelefricano93** [comment]
I'am working on the update

I have created this new input to allow you to provide your custom template

![image](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/26500344/b4e0cd60-ebd4-4e5a-ab74-7ac61ab51243)

This is an example of template, since you have some tags with html and some with no html, you are forced to created a template for each event and then provide it as input as this image

![image](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/26500344/dd1f2333-34c4-4628-9e82-0357afc24c60)

**Comment by emanuelefricano93** [comment]
Closing with [`v17.0.4`](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/releases/tag/v17.0.4)

**Comment by emanuelefricano93** [comment]
Closing with [`v17.0.4`](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/releases/tag/v17.0.4)
