### ISSUE TITLE
Date with Title 

### ISSUE THREAD

**Issue by Monali-Zala** [emanuelefricano93/frxjs-Ngx-Timeline#32]
Hello I have to implement the title with date but date should be this format like currently you was mentioned. I try but facing some issue with date So kindly give the solution. 
also i want the content-items on the righr sde
![MicrosoftTeams-image (4)](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/112300828/4beb0c20-9eaa-4740-9aa2-0579dbb27be7)

**Comment by emanuelefricano93** [comment]
Hello @Monali-Zala , to put everything on the right you can set the itemPosition of each of your events

<img width="706" alt="image" src="https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/26500344/26b99d2c-8134-4a46-93d3-4eecd46b02de">

As described in the README.md
interface NgxTimelineEvent {
  timestamp?: Date;
  title?: string;
  description?: string;
  id?: any;
  itemPosition?: NgxTimelineItemPosition;
}

this is an example

   this.events = [
      { id: 5, description: 'This is the description of the event 5', timestamp: nextYear, title: 'title 5', itemPosition: NgxTimelineItemPosition.ON_RIGHT },
      { id: 0, description: 'This is the description of the event 0', timestamp: today, title: 'title 0', itemPosition: NgxTimelineItemPosition.ON_RIGHT },
      { id: 1, description: 'This is the description of the event 1', timestamp: tomorrow, title: 'title 1', itemPosition: NgxTimelineItemPosition.ON_RIGHT },
      { id: 2, description: 'This is the description of the event 2', timestamp: today, title: 'title 2', itemPosition: NgxTimelineItemPosition.ON_RIGHT },
      { id: 3, description: 'This is the description of the event 3', timestamp: tomorrow, title: 'title 3', itemPosition: NgxTimelineItemPosition.ON_RIGHT },
      { id: 4, description: 'This is the description of the event 4', timestamp: nextMonth, title: 'title 4',itemPosition: NgxTimelineItemPosition.ON_RIGHT /*itemPosition: NgxTimelineItemPosition.ON_RIGHT */},
    ];
    
    
    
About the date i am not able to understand your problem, but you have your events and you can set the title you want to set, formatting it before creating your list

**Comment by Monali-Zala** [comment]
For the date I have to put the title with  timestamp. But we have to make sure date format is not change. This is i am trying but I am not able to solve.

**Comment by emanuelefricano93** [comment]
You should set the Date in the title using the angular date pipe

https://angular.io/api/common/DatePipe

**Comment by Monali-Zala** [comment]
But I don't want to set Date in title I want to set title in timeStamp.

**Comment by emanuelefricano93** [comment]
Try do to an example, because again you can control the title and you can set what you want .
Try to put a graphic example so I can understand

**Comment by Monali-Zala** [comment]
![title](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/112300828/e792f901-81f8-49d1-bef5-d95b94e43cac)

I have attached this image for your understanding what I want to with title and timeStamp. I want title just above the date as shown in the image.
