### ISSUE TITLE
Can we add horizontal support for this?

### ISSUE THREAD

**Issue by brock-codes** [emanuelefricano93/frxjs-Ngx-Timeline#40]

**Comment by emanuelefricano93** [comment]
What do you need exactly? Can you support the request with an image?

**Comment by brock-codes** [comment]
![simple-horizontal-timeline-css](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/168504367/c9623344-8234-4e27-a6eb-c8566df592b0)
Something like this

**Comment by emanuelefricano93** [comment]
Ok thank you I will try to reuse as much as possible what  we have know, if the timeline is too long in a first version you will need an horizontal scrollbar. 
I asked a picture just to keep things simpler as mush as possible, I will try to work on this :)

**Comment by emanuelefricano93** [comment]
Hello @brock-codes version 17.0.8 now supports horizontal behavior. It is a bit different from your example because it is reusing the previous template but you are free to customize with custom templates.
