### ISSUE TITLE
Import problem (Standalone component)

### ISSUE THREAD

**Issue by Drelaky** [emanuelefricano93/frxjs-Ngx-Timeline#42]
![image](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/53569746/32a5915e-2b34-48b7-b9c0-8fd4dc4b966d)
![image](https://github.com/emanuelefricano93/frxjs-Ngx-Timeline/assets/53569746/a2f6ef92-f19d-4b16-95ff-c55c1164d377)

How to solve my problem?

**Comment by emanuelefricano93** [comment]
Hello @Drelaky  thanks for using the library, I have just updated an example with a test standalone component importing the module with no error. You can try to see from the branch feature/standalone.
Try to check your configuration and compare it with this example branch,  I hope this will help you but it seems to be  not an issue related the library itself.
