### ISSUE TITLE
`protractor` is EOL

### ISSUE THREAD

**Issue by Rotzbua** [emanuelefricano93/frxjs-Ngx-Timeline#48]
`protractor` is end of life and trows security warnings if dependencies are installed.
Should be migrated.

## Reference

https://www.protractortest.org/#/

**Comment by emanuelefricano93** [comment]
Yes, thanks I will check if we really need or we can just remove it. I will have a look.

**Comment by emanuelefricano93** [comment]
I just deleted protractor and init cypress.
No e2e test planned yet, but at least we are ready to implement it :)
