### ISSUE TITLE
Plans to support angular 18?

### ISSUE THREAD

**Issue by Rotzbua** [emanuelefricano93/frxjs-Ngx-Timeline#49]
Angular 18 has been released. Are there plans to support it?

## Reference

https://blog.angular.dev/angular-v18-is-now-available-e79d5ac0affe

**Comment by emanuelefricano93** [comment]
Hello @Rotzbua I will try to work on this during the weekend :)

**Comment by emanuelefricano93** [comment]
Version 18.0.0 has been released
